packages:
  - name: cloud
    actions:
      - name: askAi
        runtime: "python:3.11"
        limits: 
          timeout: 5000
          memory: 256
environment:
  AGENT_ENDPOINT: ${AGENT_ENDPOINT}
  AGENT_ACCESS_KEY: ${AGENT_ACCESS_KEY}